//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace we_task.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Access
    {
        public int id { get; set; }
        public int ClientID { get; set; }
        public bool Service_1 { get; set; }
        public bool Service_2 { get; set; }
        public bool Service_3 { get; set; }
        public Nullable<int> ContactNum { get; set; }
    
        public virtual Client Client { get; set; }
    }
}
