//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace we_task.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceOrder
    {
        public int id { get; set; }
        public int ClientID { get; set; }
        public int ServiceID { get; set; }
        public int FeatureID { get; set; }
        public string Token { get; set; }
        public System.DateTime OrderDate { get; set; }
        public string Ordertype { get; set; }
        public int quantity { get; set; }
        public Nullable<int> ContactNum { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Feature Feature { get; set; }
        public virtual Service Service { get; set; }
    }
}
